from django.contrib import admin
from .models import *

admin.site.register(Calendarevent)
admin.site.register(Company)
admin.site.register(Correlation)
admin.site.register(Correlationforex)
admin.site.register(Correlationunderlying)
admin.site.register(Currency)
admin.site.register(Dividendmarketdata)
admin.site.register(Eventtype)
admin.site.register(Forexmarketdata)
admin.site.register(Market)
admin.site.register(Marketdata)
admin.site.register(Parameterset)
admin.site.register(Repomarketdata)
admin.site.register(Riskfreerateserie)
admin.site.register(Spotmarketdata)
admin.site.register(TmpDatarequest)
admin.site.register(TmpForexDatarequest)
admin.site.register(Underlying)
admin.site.register(Underlyingmarketdata)
admin.site.register(User)
admin.site.register(Volatilitymarketdata)
admin.site.register(AuthGroup)
admin.site.register(AuthGroupPermissions)
admin.site.register(AuthPermission)
admin.site.register(AuthUser)
admin.site.register(AuthUserGroups)
admin.site.register(AuthUserUserPermissions)
admin.site.register(DjangoAdminLog)
admin.site.register(DjangoContentType)
admin.site.register(DjangoMigrations)
admin.site.register(DjangoSession)
admin.site.register(Sysdiagrams)
