# Generated by Django 3.2.25 on 2024-07-16 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendarevent',
            fields=[
                ('calendareventid', models.AutoField(db_column='CALENDAREVENTID', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_column='DATE')),
            ],
            options={
                'db_table': 'CALENDAREVENT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('campanyid', models.AutoField(db_column='CAMPANYID', primary_key=True, serialize=False)),
                ('companyname', models.CharField(blank=True, db_collation='French_CI_AS', db_column='COMPANYNAME', max_length=500, null=True)),
            ],
            options={
                'db_table': 'COMPANY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currencyid', models.AutoField(db_column='CURRENCYID', primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_collation='French_CI_AS', db_column='SYMBOL', max_length=50)),
                ('name', models.CharField(blank=True, db_collation='French_CI_AS', db_column='NAME', max_length=500, null=True)),
            ],
            options={
                'db_table': 'CURRENCY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eventtype',
            fields=[
                ('eventtypeid', models.AutoField(db_column='EVENTTYPEID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='French_CI_AS', db_column='NAME', max_length=500)),
            ],
            options={
                'db_table': 'EVENTTYPE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Forexmarketdata',
            fields=[
                ('marketdataid', models.IntegerField(db_column='MARKETDATAID', primary_key=True, serialize=False)),
                ('spotvalue', models.FloatField(db_column='SPOTVALUE')),
            ],
            options={
                'db_table': 'FOREXMARKETDATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('marketid', models.AutoField(db_column='MARKETID', primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_collation='French_CI_AS', db_column='SYMBOL', max_length=50)),
                ('name', models.CharField(blank=True, db_collation='French_CI_AS', db_column='NAME', max_length=500, null=True)),
            ],
            options={
                'db_table': 'MARKET',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marketdata',
            fields=[
                ('marketdataid', models.AutoField(db_column='MARKETDATAID', primary_key=True, serialize=False)),
                ('insertiondate', models.TextField(blank=True, db_column='INSERTIONDATE', null=True)),
                ('date', models.DateTimeField(db_column='DATE')),
                ('iscutoff', models.BooleanField(db_column='ISCUTOFF')),
            ],
            options={
                'db_table': 'MARKETDATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parameterset',
            fields=[
                ('personalid', models.AutoField(db_column='PERSONALID', primary_key=True, serialize=False)),
                ('parametersetname', models.TextField(db_collation='French_CI_AS', db_column='PARAMETERSETNAME')),
            ],
            options={
                'db_table': 'PARAMETERSET',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(db_collation='French_CI_AS', max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TmpDatarequest',
            fields=[
                ('request_id', models.IntegerField(db_column='REQUEST_ID', primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_collation='French_CI_AS', db_column='SYMBOL', max_length=50)),
                ('marketsymbol', models.CharField(blank=True, db_collation='French_CI_AS', db_column='MARKETSYMBOL', max_length=50, null=True)),
                ('date', models.DateField(blank=True, db_column='DATE', null=True)),
            ],
            options={
                'db_table': 'TMP_DATAREQUEST',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TmpForexDatarequest',
            fields=[
                ('request_id', models.IntegerField(db_column='REQUEST_ID', primary_key=True, serialize=False)),
                ('currency1', models.CharField(db_collation='French_CI_AS', db_column='CURRENCY1', max_length=50)),
                ('currency2', models.CharField(db_collation='French_CI_AS', db_column='CURRENCY2', max_length=50)),
                ('date', models.DateField(blank=True, db_column='DATE', null=True)),
            ],
            options={
                'db_table': 'TMP_FOREX_DATAREQUEST',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Underlying',
            fields=[
                ('underlyingid', models.AutoField(db_column='UNDERLYINGID', primary_key=True, serialize=False)),
                ('symbol', models.CharField(blank=True, db_collation='French_CI_AS', db_column='SYMBOL', max_length=50, null=True)),
            ],
            options={
                'db_table': 'UNDERLYING',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(db_column='UID', primary_key=True, serialize=False)),
                ('username', models.TextField(db_collation='French_CI_AS', db_column='USERNAME')),
            ],
            options={
                'db_table': 'USER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Correlation',
            fields=[
                ('marketdataid', models.OneToOneField(db_column='MARKETDATAID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='rtrmax.marketdata')),
                ('value', models.TextField(db_collation='French_CI_AS', db_column='VALUE')),
            ],
            options={
                'db_table': 'CORRELATION',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Riskfreerateserie',
            fields=[
                ('marketdataid', models.OneToOneField(db_column='MARKETDATAID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='rtrmax.marketdata')),
                ('value', models.TextField(db_collation='French_CI_AS', db_column='VALUE')),
            ],
            options={
                'db_table': 'RISKFREERATESERIE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Underlyingmarketdata',
            fields=[
                ('marketdataid', models.OneToOneField(db_column='MARKETDATAID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='rtrmax.marketdata')),
            ],
            options={
                'db_table': 'UNDERLYINGMARKETDATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Correlationforex',
            fields=[
                ('correlationforexid', models.OneToOneField(db_column='CORRELATIONFOREXID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='rtrmax.correlation')),
            ],
            options={
                'db_table': 'CORRELATIONFOREX',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Correlationunderlying',
            fields=[
                ('correlationunderlyingid', models.OneToOneField(db_column='CORRELATIONUNDERLYINGID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='rtrmax.correlation')),
            ],
            options={
                'db_table': 'CORRELATIONUNDERLYING',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dividendmarketdata',
            fields=[
                ('marketdataid', models.OneToOneField(db_column='MARKETDATAID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='rtrmax.underlyingmarketdata')),
                ('value', models.TextField(db_collation='French_CI_AS', db_column='VALUE')),
            ],
            options={
                'db_table': 'DIVIDENDMARKETDATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Repomarketdata',
            fields=[
                ('marketdataid', models.OneToOneField(db_column='MARKETDATAID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='rtrmax.underlyingmarketdata')),
                ('value', models.TextField(db_collation='French_CI_AS', db_column='VALUE')),
            ],
            options={
                'db_table': 'REPOMARKETDATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Spotmarketdata',
            fields=[
                ('marketdataid', models.OneToOneField(db_column='MARKETDATAID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='rtrmax.underlyingmarketdata')),
                ('spotvalue', models.FloatField(db_column='SPOTVALUE')),
            ],
            options={
                'db_table': 'SPOTMARKETDATA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Volatilitymarketdata',
            fields=[
                ('marketdataid', models.OneToOneField(db_column='MARKETDATAID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='rtrmax.underlyingmarketdata')),
                ('value', models.TextField(db_collation='French_CI_AS', db_column='VALUE')),
            ],
            options={
                'db_table': 'VOLATILITYMARKETDATA',
                'managed': False,
            },
        ),
    ]
